COMPONENTS := libnx-Goldleaf Goldleaf

all: $(COMPONENTS)

libnx-Goldleaf:
	$(MAKE) -C /developer/components/Goldleaf/libnx-Goldleaf/nx install

Goldleaf:
	$(MAKE) -C /developer/components/Goldleaf/Goldleaf
